= コンテナイメージをECRにコピー
:imagesdir::../assets/images
:sectnums:
:sectnumlevels: 4


== ゴール

== Skopeo



== 準備 skopeo のインストール

cli がインストールされていない場合は、以下の手順でインストールしてください。
https://www.redhat.com/ja/topics/containers/what-is-skopeo


== skopeo cli を使ったコンテナイメージのコピー

skopeo を使って、OpenShiftの内部のイメージレジストリから、AWS ECRにコンテナイメージをコピーします。

=== OpenShift内部のイメージレジストリの公開

OpenShiftの内部のイメージレジストリは、デフォルトでは外部からアクセスできません。

[NOTE]
====
ワークショップ環境では、すでにイメージレジストリが公開されているため、以下の手順は不要です。
イメージレジストリに外部からアクセスできるようにするために、*cluster-admin* 権限を持つユーザで以下のコマンドを実行します。

[.console-input]
[source,bash]
----
oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
----

公開されたリポジトリのイメージ一覧を取得します。このコマンドの実行には *cluster-admin* 権限が必要です。

[.console-input]
[source,bash]
----
export TOKEN=$(oc whoami -t)
export ROUTE=$(oc get route -n openshift-image-registry -o jsonpath='{.items[0].spec.host}')
curl -k -H "Authorization: Bearer $TOKEN" "https://$ROUTE/v2/_catalog" | jq 
----
====

リポジトリのURLは以下のようになります。
---
default-route-openshift-image-registry.apps.rosa.%SUBDOMAIN%
---


=== ECR リポジトリのToken取得

共有メモに記載したトークンを利用してください。

[NOTE]
====
AWS CLI を利用してトークンを取得する場合は、以下のコマンドを実行します。

[.console-input]
[source,bash]
----
aws ecr get-login-password --region us-east-2
----
====

=== OpenShiftのToken取得

OpenShiftにCLIでログインしている場合は、`oc whoami -t` コマンドでトークンを取得できます。

[.console-input]
[source,bash]
----
oc whoami -t
----

OpenShiftコンソールからトークンを取得する場合は、以下の手順で取得します。

. OpenShiftコンソールにログイン
. 右上のユーザ名をクリック
. 「ログインコマンドをコピー」をクリック
. %USERID% と {password} を入力してログイン
. `Display Token` をクリック


=== Skopeo を使ってコンテナイメージのコピー

. ECRにログイン
+
[.console-input]
[source,bash]
----
export ECR_TOKEN=[ECRのトークン]
skopeo login --tls-verify=false -u AWS -p $ECR_TOKEN %AWSACCOUNTID%.dkr.ecr.us-east-2.amazonaws.com
----

. OpenShiftのイメージレジストリにログイン
+
[.console-input]
[source,bash]
----
oc login https://api.%SUBDOMAIN%:443 -u %USERID% -p {password}
export TOKEN=$(oc whoami -t)
skopeo login --tls-verify=false -u %USERID% -p $TOKEN default-route-openshift-image-registry.apps.rosa.%SUBDOMAIN%
----

skopeo copy docker://default-route-openshift-image-registry.apps.rosa.%SUBDOMAIN%/%USERID%-app/albumui docker://%AWSACCOUNTID%.dkr.ecr.us-east-2.amazonaws.com/%USERID%/albumui:latest

##########
skopeo login --tls-verify=false -u AWS -p `aws ecr get-login-password --region us-east-2` 654654224671.dkr.ecr.us-east-2.amazonaws.com

skopeo copy docker://default-route-openshift-image-registry.apps.rosa.rosa-lcghp.zs4d.p3.openshiftapps.com:443/user03-app/album-api:latest docker://654654224671.dkr.ecr.us-east-2.amazonaws.com/album/albumui:latest

##########

コピー元、コピー先のリポジトリにログインしていない場合、credential を指定してコピーすることができます。

[.console-input]
[source,bash]
----
oc login https://api.%SUBDOMAIN%:443 -u %USERID% -p {password}
export TOKEN=$(oc whoami -t)
export ECR_TOKEN=[ECRのトークン]
skopeo copy --src-creds %USERID%:$TOKEN docker://default-route-openshift-image-registry.apps.rosa.%SUBDOMAIN%/%USERID%-app/albumui --dest-creds AWS:$ECR_TOKEN docker://%AWSACCOUNTID%.dkr.ecr.us-east-2.amazonaws.com/album/albumui:latest
----


== (オプション）ECRのイメージを利用したデプロイ

Private な ECR に格納されたコンテナイメージを利用してオンプレミスのOpenShiftにアプリケーションをデプロイします。

=== OpenShiftにログイン

CLIを利用してOpenShiftにログインします。


=== ECR用のImage Pull Secretの作成

. OpenShiftのプロジェクトを作成
. ECRのイメージをPullするためのSecretを作成
+
[.console-input]
[source,bash]
----
oc create secret docker-registry ecr-secret --
docker-server=%AWSACCOUNTID%.dkr.ecr.us-east-2.amazonaws.com --docker-user
name=AWS --docker-password=$(aws ecr get-login-password)
----


OpenShiftのGUI または Manifest を利用してアプリケーションをデプロイします。

=== アプリケーションをデプロイ (GUIの利用)

. 左上のパースペクティブで「開発者」モードを選択
. 左のメニューで「+追加」をクリック
. 右のメニューで「コンテナイメージ」をクリック
. 外部のイメージレジストリからのイメージ名でECRのURIを入力
+
`%AWSACCOUNTID%.dkr.ecr.us-east-2.amazonaws.com/album/albumui:latest`
+
. 画面下部の「作成」ボタンをクリック

=== アプリケーションのデプロイ(Manifestの利用)

. Deploymentのマニフェストファイルを作成して適用
+
[.console-input]
[source,bash]
----
oc create deployment albumui --image=%AWSACCOUNTID%.dkr.ecr.us-east-2.amazonaws.com/album/albumui:latest --dry-run=client -o yaml > deployment-albumui.yaml

oc apply -f deployment-albumui.yaml
----
+
. Serviceのマニフェストを作成して適用
+
[.console-input]
[source,bash]
----
oc create service clusterip albumui --tcp=8080 --dry-run=client -o yaml > service-albumui.yaml

oc apply -f service-albumui.yaml
----
+
. Routeのマニフェストを作成して適用
+
[.console-input]
[source,bash]
----
oc create route edge albumui --service=albumui --port 8080 --dry-run=client -o yaml > route-albumui.yaml
oc apply -f route-albumui.yaml
----
